pet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from pets import views as pets_views

urlpatterns = [
    url(r'^$', pets_views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

pets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm

COLORS = (
    ('BN', 'brown'),
    ('BK', 'black'),
    ('WT', 'white'),
    ('GY', 'gray'),
)

ANIMAL_TYPES = (
    ('dog', 'dogs'),
    ('cat', 'cats'),
    ('bird', 'birds'),
    ('rabbit', 'rabbits'),
    ('hamster', 'hamsters'),
)

class Pet(models.Model):
    unit = models.IntegerField(default=0)
    color = models.CharField(max_length=2, default='BN', choices=COLORS)
    animal_type = models.CharField(max_length=10, default='dog', choices=ANIMAL_TYPES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.color + self.animal_type

class PetForm(ModelForm):
    class Meta:
        model = Pet
        fields = ['unit', 'color', 'animal_type']

pets/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from pets.models import Pet, PetForm

@login_required
def home(request):
    if request.user.is_authenticated:
        pets = Pet.objects.filter(owner_id=request.user.id)
        total_pets = 0
        for pet in pets:
            total_pets += pet.unit
        if request.method == 'POST':
            for pet in pets:
                pet.delete()
            form1 = PetForm()
            form2 = PetForm()
            pet1 = form1.save(commit=False)
            pet1.unit = request.POST['form1-unit']
            pet1.color = request.POST['form1-color']
            pet1.animal_type = request.POST['form1-animal_type']
            pet1.owner_id = request.user.id
            pet1.save()

            pet2 = form2.save(commit=False)
            pet2.unit = request.POST['form2-unit']
            pet2.color = request.POST['form2-color']
            pet2.animal_type = request.POST['form2-animal_type']
            pet2.owner_id = request.user.id
            pet2.save()
            return HttpResponseRedirect(reverse("home"))
        else:
            form1 = PetForm(prefix="form1")
            form2 = PetForm(prefix="form2")
        return render(request, 'home.html', {'form1': form1,
                                             'form2': form2,
                                             'pets': pets,
                                             'total_pets': total_pets})

templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Pets</title>
  </head>

  <body>
  {% if user.is_authenticated %}
    <h2>Welcome back, {{ user.username }}!</h2>
    {% if total_pets %}
    <p>You have:</p>        
    <ul>
    {% for pet in pets %}
      {% if pet.unit %}
      <li>{{ pet.unit }} {{ pet.get_color_display }} {{ pet.get_animal_type_display }}</li>
      {% endif %}
    {% endfor %}
    </ul>
    <ul>
      <li>Total = {{ total_pets }} animals</li>
    </ul>
    {% else %}
      <p>You have no pets</p>
    {% endif %}
    <form method="post" action="">
      {% csrf_token %} 
      <ul>
        <li>{{ form1 }}</li>
        <li>{{ form2 }}</li>
      </ul>
      <input type="submit" value="Update">
    </form>
    <br>
    <a href="{% url 'logout' %}">Log Out</a>
  {% endif %}
  {% block content %}{% endblock content %}
  </body>
</html>